name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    strategy:
      matrix:
        channel: [win, linux, mac] # Remove channel if not releasing (Available: win, linux, mac, web)
    env:
      # GAME: godot-template # Change game name
      CHANNEL: ${{matrix.channel}}
    steps:
      - uses: actions/checkout@v1
      - run: scripts/prepare.sh
      - run: scripts/build.sh $CHANNEL $GAME
      - run: scripts/package.sh $CHANNEL
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: build/**/*.zip
      - name: Publish Itch
        if: env.BUTLER_API_KEY && env.USER && env.GAME
        shell: bash
        env:
          BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}
          USER: ${{secrets.ITCHIO_USER}}
        run: butler push build/$CHANNEL $USER/$GAME:$CHANNEL --userversion ${GITHUB_REF/refs\/tags\//}
  github-release:
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release
      - run: ls
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            build/**/*.zip
      
